from enum import Enum

class Technologies(Enum):
    FORESTRY = 1
    AGRICULTURE = 2
    MINING = 3
    HUNT = 4
    COMBAT = 5
    BUILDING_HEALTH = 6
    BUILDING_TIME = 7
    EXTRA_MATERIALS = 8

class Upgrades:
    BUILDING_HEALTH_MULTIPLIER = 1
    BUILDING_TIME_MULTIPLIER = 1

    FOOD_MULTIPLIER = 1
    MINING_MULTIPLIER = 1
    WOOD_MULTIPLIER = 1
    HUNT_MULTIPLIER = 1
    COMBAT_MULTIPLIER = 1
    EXTRA_MATERIALS = False